In [1]:
# Standard imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

# For showing images
from IPython.display import Image

# Insert path to mavenn beginning of path
import sys
sys.path.insert(0, '../../../')

# Load mavenn
import mavenn

In [2]:
cons_ss = "CAGGTAAGT"
model = mavenn.load_example_model('mpsa_ge_additive')

In [18]:
df1 = mavenn.get_1pt_effects(func=model.x_to_phi, alphabet='dna', wt_seq=cons_ss)
df1.head()

      l c_wt c_mut        seq       phi      dphi
name
WT   -1             CAGGTAAGT  3.696576  0.000000
C0A   0    C     A  AAGGTAAGT  3.617752 -0.078824
C0G   0    C     G  GAGGTAAGT  3.355694 -0.340882
C0T   0    C     T  TAGGTAAGT  3.406354 -0.290222
A1C   1    A     C  CCGGTAAGT  3.328534 -0.368042

In [19]:
df2 = mavenn.get_2pt_effects(func=model.x_to_phi, alphabet='dna', wt_seq=cons_ss)
df2 = df2.drop(columns=["dphi"])
df2 = df2.rename(columns={'phi':'phi_12'})
df2 = df2.iloc[1:,:]
mut_names = np.array([name.split(',') for name in df2.index])
df2['mut1'] = mut_names[:,0]
df2['mut2'] = mut_names[:,1]

df2 = df2.merge(left_on="mut1", right_index=True, right=df1["phi"], how='left')
df2 = df2.rename(columns={'phi':'phi_1'})

df2 = df2.merge(left_on="mut2", right_index=True, right=df1["phi"], how='left')
df2 = df2.rename(columns={'phi':'phi_2'})
df2["phi_wt"] = df1.loc['WT','phi']

df2 = df2[["l1", "c1_wt", "c1_mut", 
           "l2", "c2_wt", "c2_mut", 
           "phi_12", "phi_1", "phi_2", "phi_wt",]]
df2["ddphi"] = df2["phi_12"] - df2["phi_1"] - df2["phi_2"] + df1.loc['WT','phi']
df2.head()

,l1,c1_wt,c1_mut,l2,c2_wt,c2_mut,phi_12,phi_1,phi_2,phi_wt,dphi_1,dphi_2,ddphi
name,,,,,,,,,,,,,
"C0A,A1C",0,C,A,1,A,C,3.249710,3.617752,3.328534,3.696576,-0.078824,-0.368042,0.000000e+00
"C0A,A1G",0,C,A,1,A,G,3.100303,3.617752,3.179127,3.696576,-0.078824,-0.517448,0.000000e+00
"C0A,A1T",0,C,A,1,A,T,3.088916,3.617752,3.167740,3.696576,-0.078824,-0.528835,0.000000e+00
"C0A,G2A",0,C,A,2,G,A,2.684331,3.617752,2.763156,3.696576,-0.078824,-0.933420,-4.768372e-07
"C0A,G2C",0,C,A,2,G,C,2.612042,3.617752,2.690866,3.696576,-0.078824,-1.005709,-4.768372e-07

KeyError: 'mut1'